### ISSUE TITLE
[1.9 - Suggestion Thread]: Post All 1.9 Related Suggestions/Tweaks Here!

### ISSUE THREAD

**Issue by Lanse505** [Resonant-Rise/ResonantRiseV4#32]
###### What is it? {Mod/Config/Script/Etc}

> Type Here
###### Suggested Mod/Config/Script

> Type Here
###### Link to Mod/Config/Script

> Link Here
###### Why Should This Be Added?

> Type here

**Comment by emberquill** [comment]
**What is it?**

> Config file

**Suggested Config**

> veinminer/tools-and-blocks.json

**Link to Config**

> It's in [my fork](https://github.com/EmberQuill/ResonantRiseV4/blob/vmtoollist/config/veinminer/tools-and-blocks.json) of this repo. I can submit a pull request if you want.

**Why should this be added?**

> Currently only vanilla tools seem to be included in the Veinminer config, so I added tools from various mods into the tool list, including pickaxes, axes, shovels, the AIOTs from Actually Additions, and the TConstruct Mattock.

**Comment by Lanse505** [comment]
If you make it a pull request then i can merge them.

Also nice seeing someone uses this thread :) 

:+1:

**Comment by Chris-Paquette** [comment]
I've made a Vein Miner list of the current tools and blocks for Build 005, while removing items from mods that are no longer in the current version. ie Modern Metals, Silent Gems, and Neo Tech. Would you like me to post it here or make a new pull request?

**Comment by Lanse505** [comment]
Make a Pull Request for Review

**Comment by LocalBoomer** [comment]
What is it? {Mod/Config/Script/Etc}

Mod

Suggested Mod/Config/Script

[Ding](https://minecraft.curseforge.com/projects/ding)

Why Should This Be Added?

A useful mod in general but for big modpacks (like RR) load times can be quite long so being able to minimise the client and still be alerted when it boots can be really helpful.

**Comment by LocalBoomer** [comment]
What is it? {Mod/Config/Script/Etc}

Mod

Suggested Mod/Config/Script

[PSIonic Upgrades](https://minecraft.curseforge.com/projects/psionic-upgrades?gameCategorySlug=mc-mods&projectID=247038)

Why Should This Be Added?

Keeping with the 'kitchen sink' theme this mod adds more stuff to the mod PSI including:

Conjure Pulsar tricks - They act like regular Conjure tricks, but they emit redstone. They require more potency.
Conjure Star - Conjures a light that emits a ray of particles along a given vector.
Particle Trail - A potency-only trick to visually display something.
Strong Raycasts - Raycasts that ignore nonsolids.
Vector Fallback - If the given vector is of length 0 or null, it returns a given fallback vector, and otherwise passes on the original vector.
Vector Rotate - Rotate a vector around another vector by an angle.
Break Loop - Trick: Die that breaks loopcasts and ends spell circles.
With Botania:
Pulse Tricks - Tricks which emulate the Drums of the Wild, Canopy, and Gathering
Form Burst - Make a mana burst
